:source-highlighter: highlightjs

= RoboCup 2023 SSL Chip Pass Challenge Rules
{docdate}
:toc:
:sectnumlevels: 0

// add icons from fontawesome in a up-to-date version
ifdef::backend-html5[]
++++
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
++++
endif::backend-html5[]

:icons: font
:numbered:

NOTE: References to the male gender in the rules with respect to referees, team
members, officials, etc., are for simplification and apply to both males and
females.

== Goals of the Technical Challenge

A key distinguishing characteristic of the Small Size League is its tight integration of software and hardware, which is crucial to create a dynamic, collaborative soccer match. The chip kick challenge goal is to develop the passing skill accuracy and endurance to enable more plays and increase ball possession time in the game.

=== Participation Requirements

All teams are eligible and encouraged to participate in this challenge.

== Procedure

* The team places its robots on the middle line and the ball on the center point.
* A FORCE_START command will be issued, and the timer will start.
* The team has *5min* to perform as many points as possible.
* After *5min* a HALT command will be issued, and the challenge is over.

=== Pass Definitions

Teams choose how they perform passes. However, a valid pass is defined as follows:

* A pass has a source, target, and shooter position.
* The source position is where a robot kicks the ball.
* The target position is where the ball stops or changes direction by more than 30 degrees.
* The shooter is the robot nearest the source position when the pass starts.
* The pass distance is the euclidean distance between the source and target position.
* The pass direction is the orientation of the `target - source` vector.

For a valid chip kick pass, besides the previous definition:

* The ball must reach at least 15cm high to be considered a valid chip pass.

== Evaluation

The team with the most valid points wins. And the passes are evaluated as follows:
* A ground pass -- +1 point
* A chip pass -- +3 points

Teams with the same number of points will share the better position. And two or more members of OC/TC will be assigned to each challenge and act as the referee. The referee has the final decision on the result. If the two referees' counts differ, the final result will be the points average.

A valid pass must meet the following constraints:

* The pass distance must be at least *1.5m*, from source to target.
* The shooter of the previous pass can not be the receiver of the current pass (this implicitly means you need *at least 3 robots*).
* The pass direction of the must differ by at least *10 degrees* from the inverted previous pass direction: latexmath:[abs(passDirection_{cur} - (passDirection_{previous} + 180°)) > 10°]
* The ball must not exceed 6.5 m/s (as defined in the tournament rules).
* The source and target should be inside field lines.


Additionally, the following rules apply:

* The number of robots is limited to *6 robots*.
* Teams are allowed and encouraged to recover the ball outside of field lines.
* Any human interference, including exchanging robots, reduces the final number of points by *10*.
* If the ball is kicked out of the field, the ball can be positioned inside. And it will count as human interference.
