#+TITLE: Game Log Event Labeling Technical Challenge
#+AUTHOR:

* Goal of the Technical Challenge

Label an SSL game log file for specific event types (with associated
metadata). Being able to detect important game events can be useful
for the decision making algorithms of the robots. Additionally, in
future years, being able to automatically label events with associated
metadata may lead to more explainable auto-ref decisions and
potentially auto commentary on a game.

* Event Types

There are two event types: instantaneous and durations. Instantaneous
events have a label associated with a specific time in the
log. Duration events have a label associated with a range of time in
the log.

** Dribbling

Detect when dribbling is occuring. This is an instantaneous event.

The following table summarizes the metadata associated with this event.

| Field        | Description                         |
|--------------+-------------------------------------|
| IsDribbling? | Is a robot dribbling in this frame? |
| Robot ID     | Which robot is dribbling            |
| Robot Team   | Which team is dribbling             |

** Ball Possession

Detect which robot/team is in control of the ball (if any). This is an
instantaneous event.

The following table summarizes the metadata associated with this
event.

| Field    | Description                                                     |
|----------+-----------------------------------------------------------------|
| State    | One of the following values: yellow-posses, blue-posses, none   |
| Robot ID | Which robot is in possession (ignored if loose state is chosen) |

The state refers to who is in control of the ball. Either yellow, blue
or no team (none). The none state applies both when the ball is free
on the field, and when the ball is under contention from opposing team
robots.

** Passing

Detect pass attempts. This is a duration event. The duration lasts
from when the ball leaves the passer and ends when the pass either
reaches the receiver or fails (out of bounds, intercepted, deflected).

| Field       | Description                                     |
|-------------+-------------------------------------------------|
| Start Time  | When did the pass start                         |
| End Time    | When did the pass end                           |
| Successful? | Did the pass reach a receiver on the same team? |
| Passer ID   | Which robot was the one who passed the ball     |
| Passer Team | Which team is passing                           |
| Receiver ID | Which robot was the intended recipient          |

** Goal Shots

Detect attempts at scoring a goal. This is a duration event. The
duration lasts from when the ball leaves the shooter and ends when the
ball either enters the goal, or is stopped/deflected by a robot.

| Field        | Description                          |
|--------------+--------------------------------------|
| Start Time   | When did the shot start              |
| End Time     | When did the shot end                |
| Successful?  | Did the shot enter the goal?         |
| Shooter ID   | Which robot took the shot?           |
| Shooter Team | Which team did the shooter belong to |


* Procedure

During the competition, two of the game logs will be labeled by the
TC. This same game log will be provided to participants of the
competition. The TC will attempt to use game logs from games where
none of the participants in this challenge played. This is to prevent
an advantage for teams that may have saved additional information in
their own log files. However, as this cannot be guaranteed, we will
require all participants to label 2 different game logs, so at most a
participant in this challenge will have competed in a single game
log. 

Participants will produce their own set of labels for this game log
and submit the file to the TC for scoring. The submitted label files
will be scored using the released scoring program. Participants will
be ranked by score, with higher scores being better.

Participants can use any approach that is automated to label the
data. In other words, you must label the data with an algorithm that
does not require human interaction. You cannot hand-label the data,
you cannot ask for human assistance, and you cannot correct the labels
produced by your software.

You may use any algorithm for labeling (rule-based, deep learning,
etc.). You can also use a non-causal labeling algorithm (i.e. your
labeling can look at future events to help label the current
event). Non-causal labeling may be useful in ambiguous situations.

The participants should label all frames with the appropriate
instantaneous event types and metadata. To ease scoring, the number of
duration events in the ground truth data will be provided to the
participants before they produce their labels. This is to avoid having
to do sequence alignment of the ground truth and participant label
files.

* Scoring

Scoring differs by event type.

** Instantaneous Event Scoring

Each instantaneous event has a state label (e.g. dribbling or
not). For each frame that matches the ground truth labels, +1
point. For each matching piece of metadata +0.5 points.

** Duration Event Scoring

Duration events main score will be calculated using the Intersection
over Union (IoU) of the start and end times. The IoU is equal to the
area of overlap over the area of the union.

\begin{equation}
IoU = \frac{\text{area of overlap}}{\text{area of union}}
\end{equation}

The IoU is guaranteed to be $\le 1$. All IoU will be added
up. Additionally, each correct piece of metadata for an event will add
+0.5 points to the score.

** Final Score

Each category will be ranked individually in order to make each label
category equally important for an overall win. Depending on the
ranking in that category, each participant will get an amount of
overall points. The amount of points is equal to $\text{number of
participants} - \text{placement}$. So that first place has the most
points, and last place has the least. For example, with 7 participants
first place would get 6 points, second place 5, etc.

Each of the category points will then be totaled to determine an
overall winner. This way each event type accuracy is equally
important, as they all contribute to the final score evenly.


* Software Tooling

** Labeler

Prior to RoboCup 2019, a simple tool for labeling existing game logs
will be released. This tool will read an SSL Game Log file and save
labeled events corresponding to times/frames in the log file. In
addition to the tool, at least one of the public game logs will have
an example label file. Teams participating the technical challenge are
encouraged to use the labeling tool to label the other public game
logs, as well as internal logs generated during their own preparation
for the competition.


** Scoring Program

Prior to RoboCup 2019, a scoring tool will be released. This tool will
compare a "ground-truth" label file with label files produced by
participants in the technical challenge and spit out a score according
to the rules defined below.


* Label File Format

This is still being defined and will be released with the software
labeling and scoring program. The file will be protobuf based, like
most of the other SSL software.
