:imagesdir: images/

= RoboCup 2021 SSL Ball Placement Technical Challenge Rules
{docdate}
:toc:

// add icons from fontawesome in a up-to-date version
ifdef::basebackend-html[]
++++
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
++++
endif::basebackend-html[]

:icons: font
:numbered:

NOTE: References to the male gender in the rules with respect to referees, team
members, officials, etc. are for simplification and apply to both males and
females.

== Goals of the Technical Challenge

Given the goal of preparing Division B teams to participate in Division A
matches, this technical challenge aims to incentive Division B teams to develop
one of the skills needed to play a match in Division A. In this case, the
challenge is to autonomously place the ball using the robots
("*AutoPlacement*").

=== Participation Requirements

All Division B teams are eligible and *must* participate in this challenge.

== Procedure

Since this challenge must be done remotely, each team is responsible to issue
the *AutoPlacement commands*. This can be easily achieved by using the SSL Game
Controller with a connected autoRef. The command can be issued using the "*Place
Ball*" button, located at the bottom left side of the GC GUI.

Also, the logs of the challenge must be recorded through the SSL Log tools and
sent to the TC.

The AutoPlacement command includes a *game state*, which can be *BallPlacementYellow*
or *BallPlacementBlue*, and the requested ball position.  Before and after
those commands the game is in Stop state, therefore, the robots are allowed to
position themselves wherever they want to, while respecting the Stop state
rules.

When the robots are done positioning, the AutoPlacement command will be issued
and the rules for this state can be found in the
link:https://robocup-ssl.github.io/ssl-rules/sslrules.html#_ball_placement[rule book].

The starting and desired positions of the ball will be sent to the teams prior
to the challenge.

Teams are allowed to use up to 6 robots.

== Evaluation

Every team places the ball in the same situations. The number and kind of
situations will be determined by the TC.

A point will be awarded for every successfully placed ball. In case of ties,
the team that was capable of placing the balls in the least amount of time
wins.

The TC reserves the right to change the evaluation procedure.
