== Competition Procedure

Each stage will consist of 3 independent trial runs by each
participant. This is to account for any random effects as well as to
allow participants to adjust in-between their trials. Scoring will be
based on overall performance among the trials for each stage, so it is
important for teams to perform consistently well.

While the particular starting configurations of the ball and the robot will be
different between stages and trial to trial, the TC member running the
competition stage will strive to make the starting conditions similar between
each participant for that trial run. This is further complicated by each team
having a remote setup. The TC running the competition will pre-determine
starting positions of ball, robot and static defender for each independent trial
ahead of the competition. These positions will be specified relative to the
common landmark of the goal. The TC will send/show a diagram with these
positions to the team during their assigned technical challenge slot and ensure
that the robot, ball and static defender are at the approximate positions before
the run begins.

Each participating team will have a slot assigned to them to complete the
challenge. The trials will be done live on video, just like the hardware
challenges teams need to provide a camera that covers the whole field.
Participants will do each stage and every trial back-to-back during their
assigned time. Teams will have a maximum of 2 hours from the start of their slot
to complete all of the trials under the supervision of the TC. Once the two
hours are finished, any unfinished trials or stages will receive a score of
zero. If teams have technical issues, they can resolve them in between trials,
keeping in mind the overall time that all trials must be completed in.

Challenges will be executed on a field of at least 4x3m with a goal size of
0.7m. See the hardware section for more details on the field setup.

Each run will start with a halt command. Just before the start, a stop command
will be given, but the robot should not move during the stop command. This is
just to allow teams a few seconds to initialize any internal state. The run will
officially start when a force start command is sent. This will start the timer
and at this point the robot may begin moving.

=== Stage 1: Grab a Stationary Ball

This stage is designed to be the easiest and demonstrate basic sensing
and control capabilities. The robot will need to detect a ball on the
field, navigate to it, and place it on its dribbler. Partial points
will be awarded, and time will be used for tie-breaking.

For each trial a random robot starting location/orientation and a random ball
starting position will have been pre-generated by the TC. Just before the trial
the TC will show the participant a diagram for the starting configuration and
the participant will configure the field as specified. Both the robot and the
ball will start stationary. There are no restrictions on the starting
configuration other than that both robot and ball will be somewhere on the
field.

Before each run the robot will begin in the halt state. A stop command
will be issued to ready the robot, but the robot should not yet
move. The run begins with a force start command at which point the
timer starts and the robot may attempt to complete the task.

The robot may move anywhere on the field within the walls. The ball
may similarly move anywhere on the field throughout the time. Each
trial will last a maximum of one minute.

==== Scoring

- Touching the ball with any part of the robot -- +1
- Touching the ball with the dribbler -- +1
- Robot stopped with ball touching dribbler at the end of the run :: +1

In the event of a tie between participants for this trial shorter
times will be used to determine ordering.

==== Differences to 2019 SSL Vision Blackout Challenge

Unlike the 2019 challenge, there are no restrictions placed on the
relative distances of the robot's start configuration and the
ball. The total time to complete each trial has also been
increased. Finally, the ball and robot may go out of bounds on the
field without ending the trial.

=== Stage 2: Scoring on an Empty Goal

This stage is designed to build on stage 1, requiring that participant
robot's can also detect/localize on a goal without the SSL vision
software. Like stage 1, the robot will need to detect a ball, move to
it and manipulate it. The robot must put the ball into the goal to
receive maximum points in the trial.

The robot and ball will start the same as in Stage 1. The TC will have
pre-generated starting positions for this stage and just before each trial show
the starting configuration diagram to the participant. The participants will
attempt to replicate this starting configuration on their field setup. In this
stage, the goal is for the robot to score on an empty goal. If the team has
multiple goals on their field, only the goal used for the initial configuration
reference point will count as scoring. While scoring the robot may not enter
the defense zone. Unlike regular gameplay the ball does not need to stay on the
ground in order for the goal to be counted.

Before each run the robot will begin in the halt state. A stop command
will be issued to ready the robot, but the robot should not yet
move. The run begins with a force start command at which point the
timer starts and the robot may attempt to complete the task. Each
trial will last a maximum of one minute. The trial will stop when the
goal has occurred or time has elapsed.

==== Scoring

- Touching the ball with any part of the robot -- +1
- Touching the ball with the dribbler -- +1
- Ball entered defense zone -- +1
- Ball entered goal -- +1
- Robot entered defense zone -- -1

=== Stage 3: Scoring on a Statically Defended Goal

This stage is a more complex version of stage 2. The goal is the same,
but now there will be a static obstacle placed somewhere inside the
defense zone. Unlike stage 2, a specific goal will be designated so
that robots can attempt to score on the statically defended goal.

The obstacle will be another robot provided by the participating team. The goal
is to be able to use local sensing to detect opponent robots in a game like
scenario.

The robot and ball will start the same as in Stage 1 and Stage
2. Unlike Stage 2, robots must only score in the designated goal. The target
goal will be on the same half that the robot starts on. While scoring the robot
may not enter the defense zone. This time the ball must enter the goal via a
flat kick to prevent kicking over the obstacle. Just as in the previous stages
the TC will have pre-generated starting configurations. These configurations
will be given to the team just before starting the trial so that the team can
configure their field to match as closely as possible.

==== Scoring

- Touching the ball with any part of the robot -- +1
- Touching the ball with the dribbler -- +1
- Ball entered defense zone -- +1
- Ball entered goal -- +1
- Robot entered defense zone -- -1
