[appendix]

== Stage Scenarios

The scenarios for each stage can be seen below, the team has 3 tries in each
scenario and there are 3 scenarios per stage, the first one being the easiest,
and the last one being the hardest.

=== Stage 1

image::../vision_blackout_scenarios/stage1_a.svg[Interactive,700,opts=interactive]
image::../vision_blackout_scenarios/stage1_b.svg[Interactive,700,opts=interactive]
image::../vision_blackout_scenarios/stage1_c.svg[Interactive,700,opts=interactive]

=== Stage 2

image::../vision_blackout_scenarios/stage2_a.svg[Interactive,700,opts=interactive]
image::../vision_blackout_scenarios/stage2_b.svg[Interactive,700,opts=interactive]
image::../vision_blackout_scenarios/stage2_c.svg[Interactive,700,opts=interactive]

=== Stage 3

image::../vision_blackout_scenarios/stage3_a.svg[Interactive,700,opts=interactive]
image::../vision_blackout_scenarios/stage3_b.svg[Interactive,700,opts=interactive]
image::../vision_blackout_scenarios/stage3_c.svg[Interactive,700,opts=interactive]
